baseURL = "https://blog.josephmorag.com/"
languageCode = "en-us"
Title = "Joseph Morag"
enableRobotsTXT = true
paginate = 8
summaryLength = 50

theme = "hugo-primer"
# available themes:
  # contrast-hugo - math works, title "Joseph Morag" is duplicated, no youtube or github icons
  # er - title box in the corner a bit weird, math broken
  # hugo-dusk - math broken, no next/prev links on posts
  # hugo-kiera - math broken, links a shitty color, otherwise good
  # hugo-primer - need to figure out TOC, about shows up in posts
  # hugo-theme-noteworthy - math wonky looking but works, no next/prev
  # Mainroad - no youtube/gh or next/prev, Lauren doesn't like it

googleAnalytics = ""
copyright = "&copy;Joseph Morag 2020"

[taxonomies]
  tag = "tags"

[author]
  name = "Joseph Morag"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "A blog about various technologies I like"
  # twitter = "Your Twitter username"
  # facebook = "Your Facebook username"
  # instagram = "Your Instagram username"
  github = "https://github.com/jmorag"
  reddit = "https://www.reddit.com/user/jmorag"
  # gitlab = "Your GitLab username"
  # npm = "Your npm username"
  # codepen = "Your CodePen username"
  # dribbble = "Your Dribbble username"
  # flickr = "Your Flickr username"
  # pinterest = "Your Pinterest username"
  # tumblr = "Your Tumblr username"
  # vimeo = "Your Vimeo username"
  youtube = "https://youtube.com/channel/UCqCd5nmIEU9u62dpq3h4bvg"
  # linkedin = "Your LinkedIn username"

[[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[[menu.main]]
    name = "RSS"
    url = "/posts/index.xml"
    weight = 4

# Most aggressive privacy settings
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true